# Generated by Django 5.0.6 on 2024-06-29 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='request',
            name='skils',
        ),
        migrations.AddField(
            model_name='request',
            name='tone',
            field=models.IntegerField(choices=[(1, 'Casual'), (2, 'Business Casual'), (3, 'Business Professional')], default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
