# Generated by Django 5.0.6 on 2024-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_remove_request_interests_remove_request_skils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
