# Generated by Django 5.0.6 on 2024-06-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uploader.prompt'),
        ),
    ]
