# Generated by Django 5.0.6 on 2024-06-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_request_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='request',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='tone',
            field=models.IntegerField(choices=[(1, 'Formal'), (2, 'Casual'), (3, 'Playful')], default=1),
        ),
    ]
